### ISSUE TITLE
data格式  ：2023-01-01

### ISSUE THREAD

**Issue by Xiaosade** [yinfuyuan/php-enum#1]
如何设置取到这样的数据格式？

**Comment by yinfuyuan** [comment]
> 

你的使用场景是什么呢？通常枚举是固定的一类值，日期属于动态值，并不适合使用枚举。

**Comment by yinfuyuan** [comment]
@Xiaosade 你的使用场景是什么呢？通常枚举是固定的一类值，日期属于动态值，并不适合使用枚举。
